### ISSUE TITLE
建议把 BARK 的发送方式改为 POST

### ISSUE THREAD

**Issue by cuteribs** [wuzhi04/MyActions#19]
目前消息长一点就会报错, 如 `京东资产变动通知`.

```
Bark APP发送通知调用API失败！！

HTTPError: Response code 431 (Request Header Fields Too Large)
    at Request.<anonymous> (/jd/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1623331557161,
    socket: 1623331557162,
    lookup: 1623331557317,
    connect: 1623331557354,
    secureConnect: 1623331557447,
    upload: 1623331557448,
    response: 1623331557490,
    end: 1623331557493,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 155,
      tcp: 37,
      tls: 93,
      request: 1,
      firstByte: 42,
      download: 3,
      total: 332
    }
  }
}
```

**Comment by wuzhi04** [comment]
之前有说过这个问题，换用企业微信吧
