### ISSUE TITLE
宠汪汪运行时报错

### ISSUE THREAD

**Issue by a620620** [wuzhi04/MyActions#35]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /jd/scripts/jd_joy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/jd/scripts/jd_joy.js:2157:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/jd/scripts/jd_joy.js' ]
运行环境 Docker

**Comment by tabs** [comment]
这个宠旺旺失效了，需要手动执行

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月30日(周三) 上午10:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wuzhi04/MyActions] 宠汪汪运行时报错 (#35)




 
internal/modules/cjs/loader.js:905
 throw err;
 ^
 
Error: Cannot find module 'canvas'
 Require stack:
  
/jd/scripts/jd_joy.js
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
 at Function.Module._load (internal/modules/cjs/loader.js:746:27)
 at Module.require (internal/modules/cjs/loader.js:974:19)
 at require (internal/modules/cjs/helpers.js:92:18)
 at Object. (/jd/scripts/jd_joy.js:2157:5)
 at Module._compile (internal/modules/cjs/loader.js:1085:14)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
 at Module.load (internal/modules/cjs/loader.js:950:32)
 at Function.Module._load (internal/modules/cjs/loader.js:790:14)
 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
 code: 'MODULE_NOT_FOUND',
 requireStack: [ '/jd/scripts/jd_joy.js' ]
 运行环境 Docker

**Comment by a620620** [comment]
我看到大佬已经更新了代码，但在docker环境下差一个node.js，不晓得咋装上去

**Comment by tabs** [comment]
用命令npm install ***@***.***&nbsp; -S
装吧
前提是x86架构,canvas需要依赖太多,有些依赖arm下不支持,你试试,祝好运！

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月30日(周三) 中午11:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wuzhi04/MyActions] 宠汪汪运行时报错 (#35)




 
我看到大佬已经更新了代码，但在docker环境下差一个node.js，不晓得咋装上去

**Comment by a620620** [comment]
你说的星号是啥？？

**Comment by tabs** [comment]
邮件回复有问题，我已经改了你看看吧
npm install ***@***.*** -S



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月30日(周三) 中午11:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wuzhi04/MyActions] 宠汪汪运行时报错 (#35)




 
你说的星号是啥？？

**Comment by a620620** [comment]
确实装不了~~缺少太多的项了

**Comment by tabs** [comment]
> 确实装不了~~缺少太多的项了

对的，我昨天我也试了试不行哈哈，我是在arm设备上失败的，x86没有试过。

**Comment by a620620** [comment]
我的虚拟机上试的，X86的~

**Comment by wuzhi04** [comment]
下午瞅瞅，有没有最新的宠往往
