### ISSUE TITLE
财富岛提现

### ISSUE THREAD

**Issue by kongren978** [wuzhi04/MyActions#4]
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './jdJxncTokens.js'
Require stack:
- /ql/scripts/raw_jx_cfdtx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ql/scripts/raw_jx_cfdtx.js:6:34)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/raw_jx_cfdtx.js' ]
}

**Comment by wuzhi04** [comment]
你没用这个库，应该是单独运行了脚本
