### ISSUE TITLE
jd_joy脚本报错

### ISSUE THREAD

**Issue by lxp1116** [wuzhi04/MyActions#7]
❗️宠汪汪, 错误!
TypeError: $.getPetTaskConfigRes.datas is not iterable
    at petTask (/jd/scripts/jd_joy.js:223:42)
    at jdJoy (/jd/scripts/jd_joy.js:104:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /jd/scripts/jd_joy.js:76:7

**Comment by wuzhi04** [comment]
下午有时间会看一下
